### ISSUE TITLE
invalid argument for "-t, --tag" flag: invalid reference format

### ISSUE THREAD

**Issue by Laurian** [fnproject/serverless-fn#5]
I'm trying the sample from serverless/fn but with a custom fnserver deployment and a custom registry, running `SLS_DEBUG=* FN_REGISTRY=http://192.168.1.22:5000/v2/ FN_API_URL=http://192.168.1.22:8080/ npx serverless deploy -v` I get 

```
invalid argument "http://192.168.1.22:5000/v2/hello:0.0.1" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
Pushing http://192.168.1.22:5000/v2/hello:0.0.1 to docker registry....
invalid reference format
/Users/laurian/Sandbox/fn-test-project/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

Error: docker command failed
    at module.exports.logError (/Users/laurian/.npm/_npx/45859/lib/node_modules/serverless/lib/classes/Error.js:92:11)
    at process.on (/Users/laurian/.npm/_npx/45859/lib/node_modules/serverless/bin/serverless:21:3)
    at process.emit (events.js:189:13)
    at /Users/laurian/Sandbox/fn-test-project/node_modules/bluebird/js/release/debuggability.js:199:33
    at activeFireEvent (/Users/laurian/Sandbox/fn-test-project/node_modules/bluebird/js/release/debuggability.js:242:44)
    at fireRejectionEvent (/Users/laurian/Sandbox/fn-test-project/node_modules/bluebird/js/release/debuggability.js:632:14)
    at Promise._notifyUnhandledRejection (/Users/laurian/Sandbox/fn-test-project/node_modules/bluebird/js/release/debuggability.js:65:9)
    at Timeout._onTimeout (/Users/laurian/Sandbox/fn-test-project/node_modules/bluebird/js/release/debuggability.js:44:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

I managed to pinpoint it to `dockerBuild()` where the args are:

```
[ 'build',
  '-t',
  'http://192.168.1.22:5000/v2/hello:0.0.1',
  '-f',
  '/Users/laurian/Sandbox/fn-test-project/hello/tempDockerFile',
  '--build-arg',
  'HTTP_PROXY',
  '--build-arg',
  'HTTPS_PROXY',
  '/Users/laurian/Sandbox/fn-test-project/hello' ]
```

`func.imageName` should be `hello:0.0.1`

**Comment by Laurian** [comment]
OK, solved, no `http://` in `FN_REGISTRY`: `FN_REGISTRY=192.168.1.22:5000/v2/` also I had to make my docker accept a non-https registry:
https://docs.docker.com/registry/insecure/#deploy-a-plain-http-registry
